---
- name: Ansible Playbook Setup
  hosts: srgade@152.7.176.237
  become: yes
  tasks:
  - name: Install nodejs
    apt:
      name: nodejs
      state: present
  - name: Install forever globally
    npm:
      name: forever
      global: yes
# clone tokens
#   environment:
#     BOTTOKEN: /var/local/BOTTOKEN
#     CSC510APIKEY: /var/local/CSC510APIKEY
#     CSC510ISSUESTOKEN: /var/local/CSC510ISSUESTOKEN
#     CSC510PULLSTOKEN: /var/local/CSC510PULLSTOKEN
#     CSC510REPOSTOKEN: /var/local/CSC510REPOSTOKEN
#     MERRIAMWEBSTERTOKEN: /var/local/MERRIAMWEBSTERTOKEN

# unable to create deploy key: https://piazza.com/class/ky09haj6kvc533?cid=532
#  - name: Pull/clone git repo into a destination
#    git:
#      repo: https://github.ncsu.edu/csc510-s2022/CSC510-17.git
#      version: main
#      key: 
#      dest: /home/gitex/
#      clone: yes
#      update: yes
  - name: Install npm packages
    shell:
      "npm install"
    args:
      chdir: /home/gitex/
