---
- name: bot setup
  hosts: all
  become: yes
  vars:
    tokens:
      GITHUB_TOKEN: "{{ lookup('env', 'GITHUB_TOKEN') }}"
      BOTTOKEN: "{{ lookup('env', 'BOTTOKEN') }}"
      MERRIAMWEBSTERTOKEN: "{{ lookup('env', 'MERRIAMWEBSTERTOKEN') }}"
      CSC510APIKEY: "{{ lookup('env', 'CSC510APIKEY') }}"
      CSC510ISSUESTOKEN: "{{ lookup('env', 'CSC510ISSUESTOKEN') }}"
      CSC510PULLSTOKEN: "{{ lookup('env', 'CSC510PULLSTOKEN') }}"
      CSC510REPOSTOKEN: "{{ lookup('env', 'CSC510REPOSTOKEN') }}"
  tasks:
  - name: setting env variables on remote
    blockinfile:
      path: /etc/environment
      block: |
        BOTTOKEN="{{ tokens.BOTTOKEN }}"
        GITHUB_TOKEN="{{ tokens.GITHUB_TOKEN }}"
        MERRIAMWEBSTERTOKEN="{{ tokens.MERRIAMWEBSTERTOKEN }}"
        CSC510APIKEY="{{ tokens.CSC510APIKEY }}"
        CSC510ISSUESTOKEN="{{ tokens.CSC510ISSUESTOKEN }}"
        CSC510PULLSTOKEN="{{ tokens.CSC510PULLSTOKEN }}"
        CSC510REPOSTOKEN="{{ tokens.CSC510REPOSTOKEN }}"
  - name: install nodejs & npm
    package:
      name: npm
      state: present
  - name: install forever
    npm:
      name: forever
      global: yes
      state: present
  - name: clone repo
    git:
      repo: https://{{ tokens.GITHUB_TOKEN }}@github.ncsu.edu/csc510-s2022/CSC510-17.git
      dest: /home/{{ lookup('env', 'USER') }}/gitex
      clone: yes
      update: yes
  - name: install node modules
    npm:
      path: /home/{{ lookup('env', 'USER') }}/gitex
  - name: check list of running apps
    become: true
    become_method: sudo
    become_user: "{{ lookup('env', 'USER') }}"
    command: forever list
    register: forever_list
    changed_when: false
  - name: start app
    become: true
    become_method: sudo
    become_user: "{{ lookup('env', 'USER') }}"
    command: forever start /home/{{ lookup('env', 'USER') }}/gitex/index.js
    when: "forever_list.stdout.find('/gitex/index.js') == -1"