---
- name: bot setup
  hosts: localhost
  become: yes
  tasks:
  - name: install nodejs & npm
    yum:
      name: npm
      state: present
  - name: install forever
    npm:
      name: forever
      global: yes
      state: present
  - name: clone repo
    git:
      repo: https://{{ lookup("env", "GITHUB_TOKEN") }}@github.ncsu.edu/csc510-s2022/CSC510-17.git
      dest: /home/srgade/gitex
      clone: yes
      update: yes
  - name: install node modules
    npm:
      path: /home/srgade/gitex
# clone tokens
#   environment:
#     BOTTOKEN: /var/local/BOTTOKEN
#     CSC510APIKEY: /var/local/CSC510APIKEY
#     CSC510ISSUESTOKEN: /var/local/CSC510ISSUESTOKEN
#     CSC510PULLSTOKEN: /var/local/CSC510PULLSTOKEN
#     CSC510REPOSTOKEN: /var/local/CSC510REPOSTOKEN
#     MERRIAMWEBSTERTOKEN: /var/local/MERRIAMWEBSTERTOKEN